### ISSUE TITLE
Enable OPL-1 license in manifest

### ISSUE THREAD

**Issue by imanie383** [Vauxoo/pylint-conf#66]
When trying to publish the apps in the odoo store, it sends us the following error:

Module not installable: Please change the license of your module from OEEL-1 to OPL-1
https://git.vauxoo.com/vauxoo/apps/uploads/6a0376c1d56b6a06fbb081c78f0f2149/image.png
![image](https://user-images.githubusercontent.com/35231827/104618055-da50cc00-5651-11eb-93ba-b9596734b1d5.png)

But when using this license in the modules: the lints send the following error:
License "OPL-1" not allowed in manifest file.
https://git.vauxoo.com/vauxoo/apps/uploads/806d5bcb711c53a210d61aeead0b4531/image.png
https://git.vauxoo.com/vauxoo-dev/apps/-/jobs/581224

![image](https://user-images.githubusercontent.com/35231827/104618024-d0c76400-5651-11eb-9869-6fc6da7dfbb1.png)

**Comment by moylop260** [comment]
@fernandahf 

Could you help me here, please?
